spring:
  # Email
  mail:
    host: smtp.gmail.com                          #Gmail의 SMTP 서버 호스트
    port: 587                                     #SMTP 서버의 포트 번호. Gmail SMTP 서버는 587번 포트를 사용
    username: saemigwon25@gmail.com               #이메일을 보내는 용으로 사용되는 계정의 이메일 주소 입력
    password: ebxm evqv pakh umgt                 #앱 비밀번호 입력
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
